(newclaim '|mysetl1| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '3) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl2| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '2) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl3| (dpi (obj) (dpi (obj) (dpi (obj) (pf (app (app '|subset| (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))))))) 'NIL)

(claim2abbrev '|bs114d|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app (app '|subsetI1| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '2) (fst '0))) (app (app '|in| '1) (fst '0))) (app (app (app (app '|binunionE| '2) '1) (fst '0)) (app (app (app (app '|binintersectER| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '3) '2)) (app (app '|binintersect| '3) '1))) (fst '0))) (app (app (app (app (app '|mysetl1| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app (app (app (app '|mysetl2| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0))))))) (app (app (app '|mysetl3| '2) '1) '0)))))
)
(newclaim '|mysetl1| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '3) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl2| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '2) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl3| (dpi (obj) (dpi (obj) (dpi (obj) (pf (app (app '|subset| (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))))))) 'NIL)

(claim2abbrev '|bs114d|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app (app '|subsetI1| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '2) (fst '0))) (app (app '|in| '1) (fst '0))) (app (app (app (app '|binunionE| '2) '1) (fst '0)) (app (app (app (app '|binintersectER| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '3) '2)) (app (app '|binintersect| '3) '1))) (fst '0))) (app (app (app (app (app '|mysetl1| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app (app (app (app '|mysetl2| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0))))))) (app (app (app '|mysetl3| '2) '1) '0)))))
)
(newclaim '|mysetl1| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '3) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl2| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '2) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl3| (dpi (obj) (dpi (obj) (dpi (obj) (pf (app (app '|subset| (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))))))) 'NIL)

(claim2abbrev '|bs114d|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app (app '|subsetI1| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '2) (fst '0))) (app (app '|in| '1) (fst '0))) (app (app (app (app '|binunionE| '2) '1) (fst '0)) (app (app (app (app '|binintersectER| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '3) '2)) (app (app '|binintersect| '3) '1))) (fst '0))) (app (app (app (app (app '|mysetl1| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app (app (app (app '|mysetl2| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0))))))) (app (app (app '|mysetl3| '2) '1) '0)))))
)
(newclaim '|mysetl1| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '3) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl2| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '2) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl3| (dpi (obj) (dpi (obj) (dpi (obj) (pf (app (app '|subset| (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))))))) 'NIL)

(claim2abbrev '|bs114d|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app (app '|subsetI1| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '2) (fst '0))) (app (app '|in| '1) (fst '0))) (app (app (app (app '|binunionE| '2) '1) (fst '0)) (app (app (app (app '|binintersectER| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '3) '2)) (app (app '|binintersect| '3) '1))) (fst '0))) (app (app (app (app (app '|mysetl1| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app (app (app (app '|mysetl2| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0))))))) (app (app (app '|mysetl3| '2) '1) '0)))))
)
(newclaim '|mysetl1| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '3) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl2| (dpi (obj) (dpi (obj) (dpi (obj) (dpi (dclass (app '|in| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0)))) (dpi (pf (app (app '|in| '3) (fst '0))) (dpi (pf (app (app '|in| '2) (fst '1))) (pf (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '5) '4)) (app (app '|binintersect| '5) '3))) (fst '2))))))))) 'NIL)

(newclaim '|mysetl3| (dpi (obj) (dpi (obj) (dpi (obj) (pf (app (app '|subset| (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))))))) 'NIL)

(claim2abbrev '|bs114d|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (app (app (app '|subsetI1| (app (app '|binintersect| '2) (app (app '|binunion| '1) '0))) (app (app '|binunion| (app (app '|binintersect| '2) '1)) (app (app '|binintersect| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '2) (fst '0))) (app (app '|in| '1) (fst '0))) (app (app (app (app '|binunionE| '2) '1) (fst '0)) (app (app (app (app '|binintersectER| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| (app (app '|binintersect| '3) '2)) (app (app '|binintersect| '3) '1))) (fst '0))) (app (app (app (app (app '|mysetl1| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0)))) (app (app (app (app (app '|mysetl2| '3) '2) '1) '0) (app (app (app (app '|binintersectEL| '3) (app (app '|binunion| '2) '1)) (fst '0)) (snd '0))))))) (app (app (app '|mysetl3| '2) '1) '0)))))
)
(claim2abbrev '|myclaim|
(lam (lam (lam (app (app (app '|subsetI1| '1) (app (app '|binunion| '2) (app (app '|binunion| '1) '0))) (lam (app (app (app (app '|binunionIR| '3) (app (app '|binunion| '2) '1)) (fst '0)) (app (app (app (app '|binunionIL| '2) '1) (fst '0)) (snd '0))))))))
)
(claim2abbrev '|myclaim|
(lam (lam (lam (app (app (app '|subsetI1| '1) (app (app '|binunion| '2) (app (app '|binunion| '1) '0))) (lam (app (app (app (app '|binunionIR| '3) (app (app '|binunion| '2) '1)) (fst '0)) (app (app (app (app '|binunionIL| '2) '1) (fst '0)) (snd '0))))))))
)
(claim2abbrev '|unionintersectDist2|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app (app '|subsetI1| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| (app (app '|binintersect| '2) '1)) (fst '0))) (app (app (app (app '|binunionE| '3) (app (app '|binintersect| '2) '1)) (fst '0)) (snd '0))) (app (app '|in| (app (app '|binintersect| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1))) (fst '0))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIL| '4) '3) (fst '1)) '0)) (app (app (app (app '|binunionIL| '4) '2) (fst '1)) '0)))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIR| '4) '3) (fst '1)) (app (app (app (app '|binintersectEL| '3) '2) (fst '1)) '0))) (app (app (app (app '|binunionIR| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| '3) '2) (fst '1)) '0)))))))) (app (app (app '|subsetI1| (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| '2) (fst '0))) (app (app (app (app '|binunionE| '3) '2) (fst '0)) (app (app (app (app '|binintersectEL| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| '3) (app (app '|binintersect| '2) '1))) (fst '0))) (app (app (app '|binunionIL| '3) (app (app '|binintersect| '2) '1)) (fst '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '4) (fst '1))) (app (app '|in| '2) (fst '1))) (app (app (app (app '|binunionE| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (snd '1)))) (app (app '|in| (app (app '|binunion| '4) (app (app '|binintersect| '3) '2))) (fst '1))) (app (app (app '|binunionIL| '4) (app (app '|binintersect| '3) '2)) (fst '1))) (lam (app (app (app (app '|binunionIR| '5) (app (app '|binintersect| '4) '3)) (fst '2)) (app (app (app (app (app '|binintersectI| '4) '3) (fst '2)) '1) '0))))))))))))
)
(claim2abbrev '|unionintersectDist2|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app (app '|subsetI1| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| (app (app '|binintersect| '2) '1)) (fst '0))) (app (app (app (app '|binunionE| '3) (app (app '|binintersect| '2) '1)) (fst '0)) (snd '0))) (app (app '|in| (app (app '|binintersect| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1))) (fst '0))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIL| '4) '3) (fst '1)) '0)) (app (app (app (app '|binunionIL| '4) '2) (fst '1)) '0)))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIR| '4) '3) (fst '1)) (app (app (app (app '|binintersectEL| '3) '2) (fst '1)) '0))) (app (app (app (app '|binunionIR| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| '3) '2) (fst '1)) '0)))))))) (app (app (app '|subsetI1| (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| '2) (fst '0))) (app (app (app (app '|binunionE| '3) '2) (fst '0)) (app (app (app (app '|binintersectEL| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| '3) (app (app '|binintersect| '2) '1))) (fst '0))) (app (app (app '|binunionIL| '3) (app (app '|binintersect| '2) '1)) (fst '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '4) (fst '1))) (app (app '|in| '2) (fst '1))) (app (app (app (app '|binunionE| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (snd '1)))) (app (app '|in| (app (app '|binunion| '4) (app (app '|binintersect| '3) '2))) (fst '1))) (app (app (app '|binunionIL| '4) (app (app '|binintersect| '3) '2)) (fst '1))) (lam (app (app (app (app '|binunionIR| '5) (app (app '|binintersect| '4) '3)) (fst '2)) (app (app (app (app (app '|binintersectI| '4) '3) (fst '2)) '1) '0))))))))))))
)
(claim2abbrev '|myclaim|
(lam (lam (lam (app (app (app '|subsetI1| '1) (app (app '|binunion| '2) (app (app '|binunion| '1) '0))) (lam (app (app (app (app '|binunionIR| '3) (app (app '|binunion| '2) '1)) (fst '0)) (app (app (app (app '|binunionIL| '2) '1) (fst '0)) (snd '0))))))))
)
(claim2abbrev '|myclaim|
(lam (lam (lam (app (app (app '|subsetI1| '1) (app (app '|binunion| '2) (app (app '|binunion| '1) '0))) (lam (app (app (app (app '|binunionIR| '3) (app (app '|binunion| '2) '1)) (fst '0)) (app (app (app (app '|binunionIL| '2) '1) (fst '0)) (snd '0))))))))
)
(claim2abbrev '|unionintersectDist2|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app (app '|subsetI1| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| (app (app '|binintersect| '2) '1)) (fst '0))) (app (app (app (app '|binunionE| '3) (app (app '|binintersect| '2) '1)) (fst '0)) (snd '0))) (app (app '|in| (app (app '|binintersect| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1))) (fst '0))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIL| '4) '3) (fst '1)) '0)) (app (app (app (app '|binunionIL| '4) '2) (fst '1)) '0)))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIR| '4) '3) (fst '1)) (app (app (app (app '|binintersectEL| '3) '2) (fst '1)) '0))) (app (app (app (app '|binunionIR| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| '3) '2) (fst '1)) '0)))))))) (app (app (app '|subsetI1| (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| '2) (fst '0))) (app (app (app (app '|binunionE| '3) '2) (fst '0)) (app (app (app (app '|binintersectEL| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| '3) (app (app '|binintersect| '2) '1))) (fst '0))) (app (app (app '|binunionIL| '3) (app (app '|binintersect| '2) '1)) (fst '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '4) (fst '1))) (app (app '|in| '2) (fst '1))) (app (app (app (app '|binunionE| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (snd '1)))) (app (app '|in| (app (app '|binunion| '4) (app (app '|binintersect| '3) '2))) (fst '1))) (app (app (app '|binunionIL| '4) (app (app '|binintersect| '3) '2)) (fst '1))) (lam (app (app (app (app '|binunionIR| '5) (app (app '|binintersect| '4) '3)) (fst '2)) (app (app (app (app (app '|binintersectI| '4) '3) (fst '2)) '1) '0))))))))))))
)
(claim2abbrev '|unionintersectDist2|
(lam (lam (lam (app (app (app (app '|setextsub| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app (app '|subsetI1| (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| (app (app '|binintersect| '2) '1)) (fst '0))) (app (app (app (app '|binunionE| '3) (app (app '|binintersect| '2) '1)) (fst '0)) (snd '0))) (app (app '|in| (app (app '|binintersect| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1))) (fst '0))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIL| '4) '3) (fst '1)) '0)) (app (app (app (app '|binunionIL| '4) '2) (fst '1)) '0)))) (lam (app (app (app (app (app '|binintersectI| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (app (app (app (app '|binunionIR| '4) '3) (fst '1)) (app (app (app (app '|binintersectEL| '3) '2) (fst '1)) '0))) (app (app (app (app '|binunionIR| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| '3) '2) (fst '1)) '0)))))))) (app (app (app '|subsetI1| (app (app '|binintersect| (app (app '|binunion| '2) '1)) (app (app '|binunion| '2) '0))) (app (app '|binunion| '2) (app (app '|binintersect| '1) '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '3) (fst '0))) (app (app '|in| '2) (fst '0))) (app (app (app (app '|binunionE| '3) '2) (fst '0)) (app (app (app (app '|binintersectEL| (app (app '|binunion| '3) '2)) (app (app '|binunion| '3) '1)) (fst '0)) (snd '0)))) (app (app '|in| (app (app '|binunion| '3) (app (app '|binintersect| '2) '1))) (fst '0))) (app (app (app '|binunionIL| '3) (app (app '|binintersect| '2) '1)) (fst '0))) (lam (app (app (app (app (app (app '|orE| (app (app '|in| '4) (fst '1))) (app (app '|in| '2) (fst '1))) (app (app (app (app '|binunionE| '4) '2) (fst '1)) (app (app (app (app '|binintersectER| (app (app '|binunion| '4) '3)) (app (app '|binunion| '4) '2)) (fst '1)) (snd '1)))) (app (app '|in| (app (app '|binunion| '4) (app (app '|binintersect| '3) '2))) (fst '1))) (app (app (app '|binunionIL| '4) (app (app '|binintersect| '3) '2)) (fst '1))) (lam (app (app (app (app '|binunionIR| '5) (app (app '|binintersect| '4) '3)) (fst '2)) (app (app (app (app (app '|binintersectI| '4) '3) (fst '2)) '1) '0))))))))))))
)
