(load "test-connect.lisp")
(scunak-connect-acl "-k mu -f bs-1-1-4d.pam")
(send-a '(HELP "bs114d") '(CLAIM))
(scunak-disconnect)
(scunak-connect-clisp "-k mu -f bs-1-1-4d.pam")
(send-a '(HELP "bs114d") '(CLAIM))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f reals.pam")
(send-a '(HELP "realSupremumProperty2") '(CLAIM))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f reals.pam")
(send-a '(HELP "realSupremumProperty2") '(CLAIM))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f reals.pam bs-chp2.pam")
(send-a '(HELP "bs-thm-2-5-4") '(CLAIM))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f reals.pam bs-chp2.pam")
(send-a '(HELP "bs-thm-2-5-4") '(CLAIM))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f reals.pam bs-chp2.pam bs-chp3.pam")
(send-a '(HELP "CauchyConvergenceCriterion") '(CLAIM))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f reals.pam bs-chp2.pam bs-chp3.pam")
(send-a '(HELP "CauchyConvergenceCriterion") '(CLAIM))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f bs-4-1-6.pam")
(send-a '(HELP "bs-4-1-6") '(CLAIM))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f bs-4-1-6.pam")
(send-a '(HELP "bs-4-1-6") '(CLAIM))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f bs-4-1-6-w-pfs.pam")
(send-a '(HELP "bs-4-1-6") '(ABBREV))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f bs-4-1-6-w-pfs.pam")
(send-a '(HELP "bs-4-1-6") '(ABBREV))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f woz1-claims.pam")
(send-a '(HELP "woz1_5") '(CLAIM))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f woz1-claims.pam")
(send-a '(HELP "woz1_5") '(CLAIM))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f woz1-lemmas.pam")
(send-a '(HELP "woz13rule4") '(ABBREV))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f woz1-lemmas.pam")
(send-a '(HELP "woz13rule4") '(ABBREV))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f woz2-claims.pam")
(send-a '(HELP "woz2B") '(CLAIM))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f woz2-claims.pam")
(send-a '(HELP "woz2B") '(CLAIM))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f woz2-lemmas.pam")
(send-a '(HELP "breln1unionCommutes") '(ABBREV))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f woz2-lemmas.pam")
(send-a '(HELP "breln1unionCommutes") '(ABBREV))
(scunak-disconnect)
(scunak-connect-acl "-k macu -f setrules.pam bool-props-sets.pam bool-props-sets-pfs.pam")
(send-a '(HELP "intersectunionTDist2") '(ABBREV))
(scunak-disconnect)
(scunak-connect-clisp "-k macu -f setrules.pam bool-props-sets.pam bool-props-sets-pfs.pam")
(send-a '(HELP "intersectunionTDist2") '(ABBREV))
(scunak-disconnect)

(scunak-connect-acl "-k f")
(send-a '(HELP "beta1") '(ABBREV))
(scunak-disconnect)
(scunak-connect-clisp "-k f")
(send-a '(HELP "beta1") '(ABBREV))
(scunak-disconnect)
(scunak-connect-acl "-k f5")
(send-a '(HELP "lam2") '(ABBREV))
(scunak-disconnect)
(scunak-connect-clisp "-k f5")
(send-a '(HELP "lam2") '(ABBREV))
(scunak-disconnect)
(scunak-connect-acl "-k ijcar2006")
(send-a '(HELP "leftInvOfInjProp") '(ABBREV))
(scunak-disconnect)
(scunak-connect-clisp "-k ijcar2006")
(send-a '(HELP "leftInvOfInjProp") '(ABBREV))
(scunak-disconnect)
